### ISSUE TITLE
Setup project in MOC cluster for this project

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#106]
As a developer, I need a project space on the MOC environment where I can host my ceph and argo for this work.

**Comment by martinpovolny** [comment]
This was resolved here:
https://github.com/operate-first/argocd-apps/pull/62
and here:
https://github.com/operate-first/apps/pull/199

**Comment by martinpovolny** [comment]
@MichaelClifford : I do not have the close button here. Please, close.

**Comment by tumido** [comment]
@martinpovolny I've added you to the repo maintainers, you should be able to see the close button now. :slightly_smiling_face:
