### ISSUE TITLE
Determine and develop method to collect PR data from testgrid 

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#108]
As data scientists aiming to analyze the entire CI process, we want to ensure that we can correlate the testgrid data with specific PR's and changes made in a given code base, so that we can potential aid in automated root cause analyses.   

This will require us to determine if its possible to use the Prow artifacts directly to identify the PR's in question, or if another tracing method is needed. In either case we will need to develop a data pipeline for collecting this data to include it in our analysis. 

Related to #105 

**Acceptance Criteria**

- [ ] Query tool (notebook ?) such that given a test run in testgrid, returns the set of changes on github.

**Comment by goern** [comment]
@xtuchyna
@pacospace

**Comment by MichaelClifford** [comment]
closing duplicate of #146
