### ISSUE TITLE
Re-build content notebook image on jupyter-lab/elyra

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#109]
As a data scientists I want to use jupyter lab and elyra on the MOC environment while developing this project so that I can use their advanced features.   

**Acceptance Criteria** 

- [ ] When the content notebook image for this repo is deployed on MOC it uses the jupyter lab/elyra image.

**Comment by goern** [comment]
can we link this feature so some release of ODH? or the image tag?

**Comment by pacospace** [comment]
> As a data scientists I want to use jupyter lab and elyra on the MOC environment while developing this project so that I can use their advanced features.
> 
> **Acceptance Criteria**
> 
> * [ ]  When the content notebook image for this repo is deployed on MOC it uses the jupyter lab/elyra image.
Hey @MichaelClifford do you want to wait until new base image of Elyra is available (the one compatible with Kubeflow Pipeline with Tekton) or do you want go ahead for now with the current Elyra image that can be used (you cannot run pipelines yet, but at least start having a look at it), WDYT?

**Comment by MichaelClifford** [comment]
@pacospace I see you already opened #127 :smile: Lets make the change now so it can start to be used, then we can update again when the new base image is available.

**Comment by pacospace** [comment]
> @pacospace I see you already opened #127  Lets make the change now so it can start to be used, then we can update again when the new base image is available.

I opened it just in case :D Let's do it!

**Comment by pacospace** [comment]
> > @pacospace I see you already opened #127  Lets make the change now so it can start to be used, then we can update again when the new base image is available.
> 
> I opened it just in case :D Let's do it!

We need a new image, I'll document this and work with the team to have it for you!

**Comment by harshad16** [comment]
The requiremnt for elyra(support by opendatahub) is to have application in python38
as the project is python36 currently and the image requires the project to be python38 
Need to fix this first: https://github.com/aicoe-aiops/ocp-ci-analysis/issues/176

**Comment by MichaelClifford** [comment]
just released v.0.0.9 and tried out content image on OPF. It works! :partying_face: Thanks @harshad16 and @pacospace
