### ISSUE TITLE
KPI Request: Test Runtime or time to Test

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#117]
As an OpenShift product manager, I would like to see the _time to test_ or the _total runtime for each test_ as it would help filter and observe tests with longer than expected runtimes.

By measuring this metric, we can observe the trend of test runtimes and check if the execution time of the tests exceed the specified values. If the execution of the test suite takes a long time, we may wish to optimize our test code or track down tests that are taking too long. This metric can also be used to draw a correlation to the tests turning out to be flaky.

**How to collect metric**

In the `TestGrid_EDA` [notebook](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/data-sources/TestGrid/testgrid_EDA.ipynb), each test is associated with a `last_run_timestamp` and each run has `fail_timestamp` as well as `pass_timestamp`.

Is there some available documentation which explains the meaning of those labels? More specifically
- Does `last_run_timestamp` mean the timestamp of the final run?
- Is there a label capturing the timestamp of the start of each passing and failing run?

**Acceptance Criteria** 

- [ ] small notebook in `notebooks/data-sources/TestGrid/metrics/` that collects this metric and stores it in ceph as a parquet.

cc: @hemajv @MichaelClifford

**Comment by MichaelClifford** [comment]
@oindrillac where is `fail_timestamp`? Probably I am blind, but I don't see it in this notebook. 

`last_run_timestamp` is probably the timestamp associated with the start time for the most recent run of a specific test on a specific grid. I'm not sure if that data will answer your question. 

We can see in the [Prow](https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-okd-4.4-e2e-aws/1355642576509603840) data in the image bellow that for each test run there is a runtime associated with it.   

![image](https://user-images.githubusercontent.com/4494906/107268356-09224e00-6a16-11eb-81ca-04a52d71e227.png)

The question is: is this info present in the testgrid data? Or do we have to step into the Prow data to get it (something I would like to avoid for this current round of work). There are a number of meta-date fields for each test run that we have not yet fully explored, and perhaps the runtime value can be found here somewhere

![image](https://user-images.githubusercontent.com/4494906/107269041-03793800-6a17-11eb-862e-3468c3e1bac0.png)

**Comment by hemajv** [comment]
@MichaelClifford When we run this cell, we see that one of the columns in the resulting data frame is `fail_timestamp`:

![Screenshot from 2021-02-08 15-16-13](https://user-images.githubusercontent.com/7343099/107276231-b601c880-6a20-11eb-9b3f-1d70f02b0581.png)

**Comment by MichaelClifford** [comment]
@oindrillac @hemajv not sure where you are at on this issue. But here is a quick answer to what is meant by `fail_timestamp` although I'm not sure if it will answer the question you are looking to answer here. 

If you go to: 
https://testgrid.k8s.io/redhat-openshift-ocp-release-4.6-informing

Click "Show Alerts" on any of the grid names, it will display some highlighted tests and includes a field for "First Failed" and "Last Passed" I'm pretty sure these are the values displayed in `fail_timestamp` and `pass_timestamp` 

![image](https://user-images.githubusercontent.com/4494906/107572545-6c4ce580-6bba-11eb-85e9-53b1b81c2239.png)

Since these values are only for the the "alert" tests I don't think it is sufficient to make a claim about the  _time to test_ or the _total runtime for each test_ for the whole platform. 

Where you able to find the test runtime any other way?

**Comment by oindrillac** [comment]
I think, fairly simple way to do this without looking into the Prow data, would be to leverage the inbuilt Graph within TestGrid for each Test in the job.

![image](https://user-images.githubusercontent.com/32435206/110703318-a2818300-81c1-11eb-8aab-9e41d806a36e.png)

These Graphs which can be toggled on and off by going to Graph>test-duration-metrics capture the time elapsed while running each test.

eg: https://testgrid.k8s.io/redhat-openshift-ocp-release-4.2-informing#release-openshift-ocp-installer-e2e-azure-4.2&graph-metrics=test-duration-minutes

The time elapsed for the test(time-duration-minutes) is plotted over time and captures values such as `24.76` minutes, time that it took to run the test.

![image](https://user-images.githubusercontent.com/32435206/110705103-e70e1e00-81c3-11eb-8be1-71172bed62b4.png)

To access the json for this, we can get it from https://testgrid.k8s.io/redhat-openshift-ocp-release-4.2-informing/table?%20\%20&show-stale-tests=&tab=release-openshift-origin-installer-e2e-aws-upgrade-rollback-4.1-to-4.2&graph-metrics=test-duration-minutes

which contains the `graphs` metadata like `"graphs":[{"metric":["test-duration-minutes"],"values":[[24.766666666666666,37.516666666666666,31.05,41.85,32.65,28.216666666666665,30.3,29.333333333333332,36.75,27.133333333333333,40.36666666666667,35.6,27,42.96666666666667,55.733333333333334,31.85,28.016666666666666]]}]`.

This should be fairly straightforward to plot in a notebook.

**Comment by hemajv** [comment]
I agree, by extracting the `test-duration-minutes` metric we can calculate other relevant information such as mean test duration time and how it can be related to the overall job.

**Comment by MichaelClifford** [comment]
@oindrillac good catch on the `&graph-metrics=test-duration-minutes`
