### ISSUE TITLE
ipynb imports failing probably due to missing bs4

### ISSUE THREAD

**Issue by chauhankaranraj** [aicoe-aiops/ocp-ci-analysis#118]
**Describe the bug**
When I try to import functions from `testgrid_EDA.ipynb` I get the following error: `ModuleNotFoundError: No module named 'bs4'`

**To Reproduce**
1. Clone repo in JupyterHub
2. Set up `pipenv` environment as described in [this](https://docs.google.com/document/d/1BUEzAeymOr1NyWQT4_vY22dFlMinjcbeV6iFBZhBTYY) doc
3. In a notebook, import any function from `testgrid_EDA` (see screenshot)

**Expected behavior**
Import works fine

**Screenshots**
![Screenshot from 2021-02-08 15-12-37](https://user-images.githubusercontent.com/15005500/107276376-e9dcee00-6a20-11eb-8c2d-fae424acc2c6.png)

**Additional context**
I think simply adding bs4 to the pipfile should fix it :man_shrugging:

**Comment by aakankshaduggal** [comment]
@chauhankaranraj installing beautifulsoup4==4.7.1 worked fine for me.

**Comment by MichaelClifford** [comment]
@chauhankaranraj do you want to update the pipfile and pipfile.lock to include bs4? 

Also, does this work when you spawn the notebook image? Or is this a problem then too? What image are you cloning the repo into on JH?

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj do you want to update the pipfile and pipfile.lock to include bs4?

Sure :+1: 

> What image are you cloning the repo into on JH?

`ocp-ci-analysis:latest`

> Also, does this work when you spawn the notebook image? Or is this a problem then too?

Sort of. It works if I run notebooks with the default ipython kernel in the notebook image, but not when I run them with the kernel that gets installed during pipenv env setup. (Or if I clone the repo locally and run).

My guess is, the default kernel didn't give this error because maybe bs4 is already baked into Thoth's base image, and the Pipfile packages are installed on top of those when creating the notebook image (just spitballing, could be wrong)

**Comment by MichaelClifford** [comment]
I wonder if the approach outlined in [the doc](https://docs.google.com/document/d/1BUEzAeymOr1NyWQT4_vY22dFlMinjcbeV6iFBZhBTYY/edit) is the best way to manage requirements any longer (wasn't  this originally a work around?). I think I was able to just `pipenv install` on a different image to get all the packages I needed.

**Comment by goern** [comment]
@pacospace  what about the deps management extension, could this be used and we create an update/addendum to the doc Michael mentioned?!

**Comment by pacospace** [comment]
> @pacospace what about the deps management extension, could this be used and we create an update/addendum to the doc Michael mentioned?!

Yes the jupyterlab extension for dependency management should be better solution, as they do not need to worry about those pipenv issues, they just open the notebook and if the kernel does not match notebook dependencies, a new kernel optimized and clean for that notebook will be created.

We use micropipenv to install dependencies (it should avoid cache problems I assume) and by default we use thoth as resolution engine.

**Comment by pacospace** [comment]
> > @pacospace what about the deps management extension, could this be used and we create an update/addendum to the doc Michael mentioned?!
> 
> Yes the jupyterlab extension for dependency management should be better solution, as they do not need to worry about those pipenv issues, they just open the notebook and if the kernel does not match notebook dependencies, a new kernel optimized and clean for that notebook will be created.
> 
> We use micropipenv to install dependencies (it should avoid cache problems I assume) and by default we use thoth as resolution engine.

we need a jupyterlab + jupyterlab-requirements image on operate first and I can demo the benefits and create a new document about those dependencies.

**Comment by chauhankaranraj** [comment]
> we need a jupyterlab + jupyterlab-requirements image on operate first and I can demo the new extension.
> On monday during thoth demo session I will show new changes and add it here: https://github.com/thoth-station/jupyterlab-requirements#demo-development-status.
> 
> I can add doc on how to use it locally and how to use it in jupyterhub directly in readme.

That'd be awesome, thanks @pacospace :smiley:

As far as this issue is concerned, should I manually add the missing package for now, and then once you've added the demo/doc, we'll just follow that going forward?

**Comment by MichaelClifford** [comment]
@chauhankaranraj looks like bs4 was added to the pipfile in #119 

I will close this issue. But moving forward lets use the Thoth approach.
