### ISSUE TITLE
Deploy workflow with existing metric notebooks 

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#124]
As a data scientists I want to have a basic workflow deployed on MOC that collects data from testgrid, processes it, and stores the processed data into Ceph, where it can be used to support an external table in hue and be visualized in Superset, so that we can operational our analysis procedures on OpenShift and make additions relatively simple. All of the code for data collection, processing and analyzing should be written as notebooks. Let's also use Argo CronWorkflows for this as it is the tooling currently provided by ODH. The first iteration of this story must not be automated or using elyra, focus shall be: do it, analyze gaps.            

Acceptance Criteria:

- [x] KFPiplines/Elyra Workflow deployed on MOC that runs daily and pushes new results to a Ceph bucket that can interact with Superset

**Comment by martinpovolny** [comment]
* we will use the same image that is being build for the project: https://quay.io/repository/aicoe/ocp-ci-analysis

* we will place argo (cron) workflows in the `manifests` subdir. We already have an ArgoCD app (that now only creates the ceph bucket request).

* @tumido published this PR https://github.com/operate-first/continuous-deployment/pull/106 that will actually enable us to deploy to the Argo namespace

* we will not follow the example that we have in `manifests/con-workflow.yml` but a new one from https://github.com/aicoe-aiops/mailing-list-analysis-toolkit/tree/master/manifests

* our workflow will use the root bucket same as is done here: https://github.com/aicoe-aiops/mailing-list-analysis-toolkit/pull/44/files

* we will not use the nbconvert but a newer approach -- "papemill" -- same as here:  https://github.com/aicoe-aiops/mailing-list-analysis-toolkit/pull/30/files

* we will run the notebooks from here:  https://github.com/aicoe-aiops/ocp-ci-analysis/tree/master/notebooks/data-sources/TestGrid/metrics



FYI: @oindrillac , @tumido

**Comment by MichaelClifford** [comment]
I was speaking with @tumido about using the new Elyra/KFP approach for the mailing list work as well for Black Flake. He brought to my attention that Elyra does not provide the ability to schedule runs. This means that it **does not support our use case** here of running daily/weekly/whatever analysis on the testgrid data. However, it does seem to do everything we need up to scheduling workflow runs. 

To proceed with this issue, we need to determine if adding the final step of scheduling is trivial and can be added manually outside of Elyra, or if we need to stick to the Argo approach.  @martinpovolny  @durandom WDYT? 

Also, don't remember writing this, but there is an explicit call in the issue description to _not_ use elyra at this stage, anyone recall why?  
>The first iteration of this story must not be automated or using elyra, focus shall be: do it, analyze gaps.
 

 @oindrillac @Shreyanand

**Comment by Shreyanand** [comment]
This [issue](https://github.com/elyra-ai/elyra/issues/471) on Elyra seems relevant. It seems it'll  be added by April 22, 2021 given in the milestones [here](https://github.com/elyra-ai/elyra/milestone/30).

**Comment by oindrillac** [comment]
Given that we will have the scheduling available in Elyra in the next release, should we be focusing on running the workflow using Elyra, or stick to Argo in this iteration ?

**Comment by MichaelClifford** [comment]
Thanks for the link @Shreyanand. In that case, I think it might makes sense to go ahead and set up our workflow using Elyra/KFPipelines and run it manually for a while until we can include the recurring schedule part in April.

I don't really like the idea of relying on or being blocked by another project, but since we are moving towards using Elyra/KFP as part of ODH anyways, it seems like it would be duplicate work to set it up with Argo, just to replace it with Elyra in a few weeks.

But I'm interested to hear what others have to say on this issue : ) 

@durandom @martinpovolny

**Comment by MichaelClifford** [comment]
I think that whats important about this issue, getting a workflow with all current KPI notebooks running and pushing data to ceph, has been accomplished. The only thing preventing this card from being "done" is the superset requirement, which we know is blocked #219  

I suggest we close this issue now and address the superset connection later on.

**Comment by ptitzler** [comment]
I realize the issue is already closed but I wanted to document that the Elyra CLI now supports running of pipelines: https://elyra.readthedocs.io/en/latest/user_guide/pipelines.html#running-a-pipeline-using-the-command-line. (Previously this was only possible through the UI)

Therefore users have now two options to schedule pipeline runs:
 - In the Kubeflow Pipelines UI 
   - In the Elyra Pipeline Editor export the pipeline as a YAML
   - In the Kubeflow Pipelines UI import the exported pipeline
   - In the Kubeflow Pipelines UI schedule a [periodic] run
 - Using any scheduler that can invoke the Elyra CLI
