### ISSUE TITLE
create list of KPI's with documentation on what they mean.

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#125]
As a data scientist, I want to have a clear understanding of what each of the candidate KPIs means, so that I can figure out how to calculate them in a jupyter notebook.

As a project manager, I want to have a clear understanding of what each of the candidate KPIs means, so that I can better help determine which ones would be the most meaningful to use for this project.

**Acceptance criteria**
- [x] If there are any KPIs that were listed in the [market research doc](https://docs.google.com/document/d/1Db8lX2GsSzHPGPtF9YooMH798jBfNHDSdOHweQD5Pj8/) but not in the [KPIs list/spreadsheet](https://docs.google.com/spreadsheets/d/1AOm_twz_djgEEZWXTummLb8IXCcoNF3xN-fyxfsdXhE/), then add them there
- [x] Add short descriptions for each item in the KPIs spreadsheet

**Comment by aakankshaduggal** [comment]
We are currently working on the spreadsheet to gather all the information regarding the KPIs. 
Please find the spreadsheet [here](https://docs.google.com/spreadsheets/d/1AOm_twz_djgEEZWXTummLb8IXCcoNF3xN-fyxfsdXhE/edit?usp=sharing)

cc : @chauhankaranraj , @martinpovolny

**Comment by MichaelClifford** [comment]
@aakankshaduggal It looks like the current list contains KPI's from only 2 sources, Tricents and Logigear. These aren't included in our [list of companies](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/docs/aiml-cicd-market-research.md). 1) Should they be included? 2) Do we still need to go through the list of potential KPI's from our research list or are they also reflected in this spreadsheet already and we just need to add the company attribution?

**Comment by MichaelClifford** [comment]
We moved the the most up to date working document for the KPI list [here](https://docs.google.com/spreadsheets/d/119WYsJU8ToTYOYP11lc6j_PdPefHXcfP5DCJjYzjrxQ/edit#gid=0) .


FYI @martinpovolny @Shreyanand @aakankshaduggal @chauhankaranraj

**Comment by MichaelClifford** [comment]
The list of KPI's, descriptions and sources can be found [here](https://docs.google.com/spreadsheets/d/119WYsJU8ToTYOYP11lc6j_PdPefHXcfP5DCJjYzjrxQ/edit#gid=0).

This should probably me treated as a living document that we will improve and add to as this project evolves, but the current version can constitute the current final draft. As such I will also consider this issue closed. :smiley:
