### ISSUE TITLE
Create Blog Article how a Data Scientist and a DevOps engineer collaborate on a massive data wrangling pipeline

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#126]
Provide documentation for work associated with #124 so that another data scientists could easily reproduce with  a new project

**Comment by hemajv** [comment]
recently gave a talk at devconf on the topic "Data Science meets DevOps", I think some of the material from the slides can be a good resource: https://docs.google.com/presentation/d/11VyqR1Ll3_FufOZzXesK5frJQdL4hIymOg1ksZZPXbQ/edit?usp=sharing
