### ISSUE TITLE
Error running tesgrid_EDA notebook

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#128]
**Describe the bug**
Error running the cell In [5]: in `testGrid_EDA` notebook

**To Reproduce**
1. Spawn up a JH MOC Server, clone the repo and install dependencies
2. Run the `testgrid_EDA` notebook
3. Run cell In [5]
```
html = BeautifulSoup(response.content)
testgrid_script = html.findAll("script")[3]
testgrid_script = testgrid_script.text.split()[5].split(",")
dashboard_names = [x.split(":")[1] for x in testgrid_script if "name" in x]
dashboard_names
```
4. Gives following error
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-10bd3c76bea3> in <module>
      1 html = BeautifulSoup(response.content)
      2 testgrid_script = html.findAll("script")[3]
----> 3 testgrid_script = testgrid_script.text.split()[5].split(",")
      4 dashboard_names = [x.split(":")[1] for x in testgrid_script if "name" in x]
      5 dashboard_names

IndexError: list index out of range
```
**Expected behavior**
The cell should run successfully and output a list of `dashboard_names`

**Screenshots**
![image](https://user-images.githubusercontent.com/32435206/107785260-5c4c1780-6d1a-11eb-88c1-f56ee312d396.png)

Has the structure of the source html changed?

**Comment by MichaelClifford** [comment]
Thanks @oindrillac looking into it. :smile:   My first guess is that is has to do with the bs4 package (since it was recently added to the Pipfile) and seeing if were importing a different version than was used earlier, since I can see that data and it looks right, but the call to `testgrid_script.text` is returning an empty string, which is not right.
