### ISSUE TITLE
KPI Request: Flake Severity

### ISSUE THREAD

**Issue by Shreyanand** [aicoe-aiops/ocp-ci-analysis#138]
As an Openshift developer or manager, I would like to gauge the level of flake severity. Some tests would be flaky for a lot of builds  and thus have a high flake rate or severity and vice versa. This metric can be leveraged to help prioritize the work needed to resolve the flake issues.

**Acceptance criteria**
- [ ] small notebook in `notebooks/data-sources/TestGrid/metrics/` that collects this metric and stores it in ceph as a parquet

**Comment by MichaelClifford** [comment]
Can this metric be derived from the data in this notebook? `/notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb`

I think if we are looking at the "flake rate of a test" we can just aggregate the output of the above notebook by test to get this value. This could be done as an extension to that notebook, but could also be done as a dashboard directly in Superset.   

![image](https://user-images.githubusercontent.com/4494906/109705891-49cd3d00-7b66-11eb-9f1c-0460c6638241.png)

**Comment by Shreyanand** [comment]
Ah! Didn't see this, but this makes sense. Do you think a quick PR to add a cell to this notebook should be good for this?

**Comment by MichaelClifford** [comment]
Yeah, I think we should add a cell with the "Severity" (flake rate by test) as a dataframe head output, with a note indicating that it will be displayed using Superset moving forward. 

Basically show the metric, but we shouldn't need to store an additional data set or create an new column.
