### ISSUE TITLE
Data Source: Bugzilla

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#145]
In addition the testgrid data (which is ultimately a higher order signal telling us which of a set of tests passed or failed during a CI run) we want to be able to connect bugs and their content  with specific failures seen in CI. This can help us track a number of important KPI's/metrics regarding the health of our project as well as support automated root cause analysis work. 

Since Red Hat hosts its own bugzilla (and I believe its public) we should be able to leverage this data for this project. However, we only care about the Bugzilla's related to the OpenShift CI data from testgrid.   

Write a notebook that, given a set of "linked_bugs" from the testgrid data, return a dataframe with the bugzillas. 1 per row, with columns for each relevant field.  

[Red Hat Bugzillas](https://bugzilla.redhat.com/page.cgi?id=fields.html)   

**Acceptance Criteria** 

- [x] Notebooks for collecting bugzilla data from https://bugzilla.redhat.com based on "linked_bugs" field in testgrid data.
- [x] EDA on bugzillas - just relevant fields and structure, not analysis of contents 
- [x] Small sample data set available in repo

**Comment by chauhankaranraj** [comment]
So far we've seen that `linked_bugs` is empty for all the Red Hat dashboards. And the conversations [here](https://coreos.slack.com/archives/C01CQA76KMX/p1617031694270300) and [here](https://coreos.slack.com/archives/CBN38N3MW/p1617030012376700), seem to confirm this. So we were considering two approaches to establish the testgrid test <--> bugzilla mapping:
1. Scrape bugzilla comments and fields to look for mentions of testgrid test names or dashboards (as per the suggestion [here](https://coreos.slack.com/archives/C01CQA76KMX/p1617040610274200?thread_ts=1617031694.270300&cid=C01CQA76KMX)). 
2. Get linked_bugs from sippy dashboards (because sippy already has this, see below), and then connect that bug with corresponding tab/test on testgrid by obtaining the tab/test information from sippy.
![Screenshot from 2021-04-01 12-41-53](https://user-images.githubusercontent.com/15005500/113326654-f7f41000-92e7-11eb-9468-f496c5b77a8b.png)

Right now we're leaning towards option 2 coz that seems to do, but WDYT team?
cc @hemajv @aakankshaduggal @MichaelClifford

**Comment by MichaelClifford** [comment]
@chauhankaranraj any idea how Sippy is managing the connection between bugzilla and testgrid? I thought they were working off of a similar data source as us (test grid). It might be worth spending some more time looking into their approach. 

To be honest, I would prefer to **not** add a dependency on another project. Are there any other options than scrape all of bugzilla and attempt to match relevant bugs?

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj any idea how Sippy is managing the connection between bugzilla and testgrid? I thought they were working off of a similar data source as us (test grid). It might be worth spending some more time looking into their approach.

We spent some time looking into the Sippy codebase (specifically, [these](https://coreos.slack.com/archives/C01CQA76KMX/p1617294775328400?thread_ts=1617031694.270300&cid=C01CQA76KMX) pointers that W Trevor King gave), but so far it isn't entirely clear to us how they're linking bugs. But yeah we can try digging deeper into it.

> To be honest, I would prefer to **not** add a dependency on another project. Are there any other options than scrape all of bugzilla and attempt to match relevant bugs?

That's fair. Although, I think based on the conversations linked above, using Sippy's `linked_bugs` label and scraping bugzilla might be the two "best" options we have :confused:

**Comment by MichaelClifford** [comment]
>That's fair. Although, I think based on the conversations linked above, using Sippy's linked_bugs label and scraping bugzilla might be the two "best" options we have confused

I think using bugzilla would be fine, but I don't think it would be a good idea to make Sippy a dependency. Which is to say, I think we should try to see if there is another way to get this data (maybe its in the gcs?), otherwise, I think scraping bugzilla is probably the way to go.  

@chauhankaranraj

**Comment by hemajv** [comment]
After digging into the Sippy code base, we were able to identify where the bugs corresponding to each test in TestGrid were being found. The bugs are being found by querying the [URL](https://search.ci.openshift.org/v2/search) mentioned [here](https://github.com/openshift/sippy/blob/df599dc08869bf2b8107e08398682ed2e16ad971/pkg/buganalysis/cache.go#L230). 

A query is made to the [search.ci.openshift](https://search.ci.openshift.org/?search) URL by passing the test and job names as parameters. The query then returns the associated bug IDs. For eg: [this query](https://search.ci.openshift.org/?search=%5C%5Bsig-network%5C%5D+pods+should+successfully+create+sandboxes+by+getting+pod&maxAge=336h&context=1&type=bug%2Bjunit&name=periodic-ci-openshift-release-master-ci-4.6-upgrade-from-stable-4.5-e2e-azure-ovn-upgrade&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job), returns all the bug IDs associated with the test `\[sig-network\] pods should successfully create sandboxes by getting pod` and for job `periodic-ci-openshift-release-master-ci-4.6-upgrade-from-stable-4.5-e2e-azure-ovn-upgrade`.

We can then use these bug IDs to scrape bugzilla and fetch relevant information related to the bugs such as components affected, status, bug reported date, product, platform etc. These bugs are present across multiple tests and jobs and we can generate a data set which aggregates all of this information. We have a [WIP notebook](https://github.com/chauhankaranraj/ocp-ci-analysis/blob/bugzilla/notebooks/data-sources/Bugzilla/bugzilla_EDA.ipynb) and are working on generating the aggregated data being collected.
