### ISSUE TITLE
Understand the testgrid ecosystem

### ISSUE THREAD

**Issue by durandom** [aicoe-aiops/ocp-ci-analysis#15]
Have a look at https://github.com/GoogleCloudPlatform/testgrid and the video linked from there.
Testgrid already applies some logic to the test runs, like identifying boards with flaky tests, or boards without tests reporting in. You can also report some additional metrics like test coverage.

1. is there a central definition for the data uploaded to RH testgrid? Test status, name, infra (gws)
2. is there some tooling to download the data from testgrid, in python? 
3. is there some prior work on analyzing testgrid data at scale? blogs?

**Comment by durandom** [comment]
cc @bparees

**Comment by bparees** [comment]
> is there a central definition for the data uploaded to RH testgrid? Test status, name, infra (gws)

we upload junit files and i guess some metadata about the job the junit is from, testgrid does the rest (as best i understand it, i don't have a deep understanding of how our job data gets ingested by testgrid).  Not sure what you mean by "infra".  We determine what platform (aws, gcp, etc) the job ran on simply by parsing the job names.

> is there some tooling to download the data from testgrid, in python?

yes, the same way sippy does it. it's not the nicest format to process though.  The relevant code is more or less here:
https://github.com/openshift/sippy/blob/46ad8d209ed1f4b8d5e5e6fa8033088a593d695c/main.go#L49-L249


> is there some prior work on analyzing testgrid data at scale? blogs?

google has some frontends that allow searching and processing of the test data, we don't have access to it for our testdata and it's not open source:

https://storage.googleapis.com/k8s-gubernator/triage/index.html

**Comment by MichaelClifford** [comment]
IIUC, testgrid is another reporting tool that provides a high level view of tests' passes/fails over time. But if we are trying to get to the ground truth, aren't the [ci logs stored in google](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-4.6/1291269757735014400/) that populate the prow dashboards what we should be looking at?

**Comment by bparees** [comment]
> IIUC, testgrid is another reporting tool that provides a high level view of tests' passes/fails over time. But if we are trying to get to the ground truth, aren't the ci logs stored in google that populate the prow dashboards what we should be looking at?

yes, technically the individual job logs + junit xml output are "ground truth", testgrid is an aggregation of that, and sippy is an aggregation/re-slicing of that.

**Comment by MichaelClifford** [comment]
> yes, technically the individual job logs + junit xml output are "ground truth", testgrid is an aggregation of that, and sippy is an aggregation/re-slicing of that.

ok, great. Thanks for the clarification. I think I now see how all these things fit together :smile: 

In either case, I think the raw data is complex enough that starting to see what we have access to and what kind of additional analyses we can do at these aggregation levels (sippy and testgrid) is a good place to get start before trying to do anything with the logs. 

> yes, the same way sippy does it. it's not the nicest format to process though. The relevant code is more or less here:
https://github.com/openshift/sippy/blob/46ad8d209ed1f4b8d5e5e6fa8033088a593d695c/main.go#L49-L249
 
Thanks for this too, very helpful for getting at the testgrid data. 

> 2. is there some tooling to download the data from testgrid, in python?

I think I should be able to adapt the [above](https://github.com/openshift/sippy/blob/46ad8d209ed1f4b8d5e5e6fa8033088a593d695c/main.go#L49-L249) easy enough into python for downloading test grid data. 

So next steps for me is to write a short notebook accessing and outlining whats available in the in the testgrid ecosystem.

**Comment by MichaelClifford** [comment]
>Have a look at https://github.com/GoogleCloudPlatform/testgrid and the video linked from there.
Testgrid already applies some logic to the test runs, like identifying boards with flaky tests, or boards without tests reporting in. You can also report some additional metrics like test coverage.

> is there a central definition for the data uploaded to RH testgrid? Test status, name, infra (gws)

I think this [config doc](https://github.com/GoogleCloudPlatform/testgrid/blob/master/config.md#prow-job-configuration) outlines the definition of whats on the testgrid. Also working on a small PR to examine the additional metadata beyond the grid values themselves that should show what data is uploaded  to TestGrid.  

> is there some tooling to download the data from testgrid, in python?

It looks like the pre-existing tooling has been written by the Sippy team in GO, but in the notebooks attached to this Issue I have adapted them in python. 

> is there some prior work on analyzing testgrid data at scale? blogs?

Not that I could find.
