### ISSUE TITLE
Define Metric collection notebook template

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#162]
We want to make sure that understanding the metrics we are collecting is straight forward. We also want to provide a template notebook to make contributing additional metrics easy.

The template should provide python code for reading data from the json format output by `/notebooks/data-sources/TestGrid/testgrid_EDA.ipynb`, a simple metric aggregation example, and code that writes the metric to disk and to Ceph as a parquet file.

Before writing a template from scratch please review the existing metric notebooks and see if there is one that can be modified to serve as the template. 

**Acceptance Criteria**    

- [ ] Template notebook for collecting and storing testgrid metrics
- [ ] Add Template to operate first website to  welcome new contributions

**Comment by oindrillac** [comment]
Can we add to the acceptance criteria - Add this to operate first website with the intention of welcoming metric notebook contributions?

**Comment by MichaelClifford** [comment]
@oindrillac its done :+1:

**Comment by Shreyanand** [comment]
@MichaelClifford Do you know if we have access to a Ceph bucket? I saw this [issue](https://github.com/aicoe-aiops/ocp-ci-analysis/issues/123) but I couldn't access the credentials...
cc @hemajv @oindrillac

**Comment by hemajv** [comment]
Seems like the bucket was created prior to migrating to the zero cluster and I think they need to be recreated on the zero cluster.
@4n4nd pointed out that there are some ongoing issues related to this: https://github.com/operate-first/support/issues/122

**Comment by MichaelClifford** [comment]
>CM is here: https://console-openshift-console.apps.cnv.massopen.cloud/k8s/ns/ds-black-flake/configmaps/black-flake
secret is here: https://console-openshift-console.apps.cnv.massopen.cloud/k8s/ns/ds-black-flake/secrets/black-flake

@Shreyanand did you change `cnv` to `zero` in the URLs?

@martinpovolny is this the case that the Ceph buckets are still not deployed on operate 1st? Or do we have a bucket deployed that we can use for storing these metrics?

**Comment by 4n4nd** [comment]
I have manually created the bucket so the creds should be available now at:
secret: https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/ds-black-flake/secrets/black-flake
configmap: https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/ds-black-flake/configmaps/black-flake

**Comment by Shreyanand** [comment]
@4n4nd Thanks, can connect to the bucket now.

**Comment by tumido** [comment]
> Seems like the bucket was created prior to migrating to the zero cluster and I think they need to be recreated on the zero cluster.
> @4n4nd pointed out that there are some ongoing issues related to this: [operate-first/support#122](https://github.com/operate-first/support/issues/122)

The issue is on your end, https://github.com/aicoe-aiops/ocp-ci-analysis/issues/164

The manually created bucket won't allow you for external access as explained here: https://github.com/operate-first/support/issues/123  Please use a different storage class, then you will have an external route available.

**Comment by 4n4nd** [comment]
Once the storageclass is updated, I think we will need to recreate the bucket

**Comment by tumido** [comment]
@4n4nd unfortunatelly a storage class **can't** be updated. You need to delete the resource and create it again, now with the new storage class instead.

**Comment by 4n4nd** [comment]
@Shreyanand the storageclass was updated and the bucket was recreated. 
The new bucket should be available externally at this host: https://s3-openshift-storage.apps.zero.massopen.cloud/
