### ISSUE TITLE
Make changes to Data Download and testgrid_labelwise-encoding to account for Graph

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#171]
**Is your feature request related to a problem? Please describe.**
As per comment in #163, "Can you collect and store these value for every grid?", there needs to be changes in existing scripts in order to add the required "graph" column in the all grids .json.

To run the time duration metric on the entire dataset, we need to make changes in the data download section in `testgrid_EDA.ipynb` and `testgrid_labelwise_encoding` method in `number of flakes.ipynb` to account for the additional "graph" key in the data.

**Describe the solution you'd like**
* make changes in the data download section in `testgrid_EDA.ipynb` to download from a different URL which will also fetch graph parameters by adding `&graph-metrics=test-duration-minutes` to the url.
* make changes in download section to include "graph" in the downloaded json.
* add a new json to the repository with the "graph" parameter which can be ingested in `time_to_test.ipynb`.
* make changes to the `testgrid_labelwise_encoding` method in `number of flakes.ipynb` to account for the additional "graph" key in the data.
* make required updates in notebooks using the function due to the change in the result schema.

**Comment by MichaelClifford** [comment]
@oindrillac @hemajv given #168, the complete metadata exploration, does it make sense to include the recommend fields into the updated data download process here as well?

**Comment by hemajv** [comment]
Most of the recommended fields seems to provide additional information related to Prow. However, I don't think these additional metadata are very much essential for the existing KPI notebooks, but perhaps they may seem more important when we start digging into further CI analysis for Prow.

**Comment by oindrillac** [comment]
+1 to what @hemajv said. Also currently, in the downloaded grids, we are mainly storing test level metadata for analyzing test level metrics. So, unless we feel the need to expand to Job level metadata,  I dont see a real need to store a much larger dataset and a support more complex schema. Perhaps, we can look into including the job level metadata that was explored in the metadata notebook as we feel the need it for it while exploring more KPIs.

**Comment by MichaelClifford** [comment]
:+1: Sounds good, So maybe down the road we should have a seperate collection process for the Job level data?
