### ISSUE TITLE
Upgrade Project dependencies to Python 3.8

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#176]
**Is your feature request related to a problem? Please describe.**
To run the Elyra Pipelines, we will need to work on the Elyra 0.0.6 image which currently supports Kubeflow. That particular image supports Python 3.8 and the current environment of the project is Python 3.6. To be able to run the notebooks in the Elyra 0.0.6 image, we would need to upgrade to Python 3.8

**Describe the solution you'd like**
Upgrade project's python env to 3.8

**Other Solutions Considered**
Although we might be able to submit jobs/workflow on that image, using our pre-built project quay image, we will need to switch images to "work" on notebooks and "submit" and run Elyra Pipelines. 

Therefore, an Upgrade or a consistency in Python versions is essential.

related to #124 
cc: @Shreyanand @pacospace

**Comment by pacospace** [comment]
Related: https://github.com/aicoe-aiops/ocp-ci-analysis/issues/109. At the end this project will have its own custom image with Elyra. cc @harshad16

**Comment by oindrillac** [comment]
@MichaelClifford is it okay to upgrade dependencies to 3.8 for this project. Is there a reason why we should stick to 3.6?

**Comment by harshad16** [comment]
There is a pr for this one: https://github.com/aicoe-aiops/ocp-ci-analysis/pull/141

**Comment by MichaelClifford** [comment]
@oindrillac I do not see any reason why we cannot update the project to 3.8, but let's try and get #141 merged.
