### ISSUE TITLE
Data Visualization Notebook

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#217]
We want to have a way of providing reporting and visualization of our collected metrics and KPI's independent of other services like superset. To achieve that, we should create a visualization notebook that reads the collected metrics from ceph and produces a time series plot for each metric we've defined [here](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/data-sources/TestGrid/metrics/README.md) that shows the change in the metric values of over time. 

**Acceptance Criteria:**

- [x] Notebook that includes a time series plot for each metric aggregated to entire platform level. 

See #275 for additional discussion.

**Comment by chauhankaranraj** [comment]
Hey team, we were trying to read the KPI metrics from the operate-first s3 storage using [these](https://github.com/operate-first/support/issues/165#issuecomment-810337239) credentials and bucket, but couldn't find most of the KPI metrics in there. Of the ones that were in there, most did not have the correct prefix i.e. `metric` (see screenshot). Am I looking at the wrong place or missing something obvious?

![Screenshot from 2021-04-14 11-47-48](https://user-images.githubusercontent.com/15005500/114739847-43aaae80-9d17-11eb-990a-e170b3b17af1.png)

cc @aakankshaduggal @isabelizimm @MichaelClifford @Shreyanand @oindrillac @hemajv

**Comment by oindrillac** [comment]
@chauhankaranraj I went through the paths that we are saving to within each notebook and observed certain inconsistencies, so that could be one of the reasons for what you are seeing above.

I opened #223 to fix those.

I think another reason could be the difference in our .env configs, or that we are using different buckets/endpoints. I remember using the test public bucket which was created for the elyra workflow to run the notebooks and thats probably why you are not seeing some metrics in the opf-datacatalog bucket.

Also re-running all acc. to #223 should fix those.

**Comment by oindrillac** [comment]
@chauhankaranraj I re-ran all the notebooks with the updated paths and you should now be able to see the metric files, to proceed with visualization.

![image](https://user-images.githubusercontent.com/32435206/114767590-cfcbce80-9d35-11eb-8b7b-df9f1954c6b1.png)

The `correlated_failures` analysis notebook takes about 2 hrs to run, so once that completes running, and the metrics are on s3, I will push the changes to the repo.

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj I re-ran all the notebooks with the updated paths and you should now be able to see the metric files, to proceed with visualization.

Great, thanks!

**Comment by hemajv** [comment]
@chauhankaranraj @aakankshaduggal @isabelizimm are you planning to use [Plotly Dash](https://plotly.com/dash/) for your visualizations in the notebook?

**Comment by isabelizimm** [comment]
I was looking into using the widgets available in-notebook. After playing around with it some, they're a bit clunky to integrate, but doable. Is Plotly Dash a better alternative?

**Comment by hemajv** [comment]
@isabelizimm what widgets are you referring to? [Plotly](https://plotly.com/python/getting-started/) is an interactive web-based visualization library that supports a wide range of charts. The plotly charts can also be rendered within a notebook through ipywidgets. To render it in a more dashboard like manner, [Dash](https://dash.plotly.com/installation) is used which renders the graphs/charts via a web app.

The nice part of Plotly is that since its built in JavaScript, there seems to be an [integration available with Gatsby](https://janosh.dev/blog/gatsby-interactive-plots), allowing us to have the visualizations incorporated into our operate-first website as well. We will have to dig into it a bit more to see how it can be done, but seems like it would be worth trying out Plotly :smiley:

**Comment by aakankshaduggal** [comment]
So we tried making some graphs using plotly but looks like Jupyterlab is not compatible with plotly. It requires an additional extension to render stuff on jupyterlab, but we were not able to install it correctly. We are trying our way around to make plotly work and hence experiencing some delays.  :disappointed: 
cc : @chauhankaranraj @isabelizimm @MichaelClifford

**Comment by MichaelClifford** [comment]
@aakankshaduggal is it a known jupyterlab extension? We can request additional extensions be included in the jupyterlab images. see https://github.com/thoth-station/s2i-generic-data-science-notebook/issues/15

**Comment by hemajv** [comment]
Yes, for plotly to work on JupyterLab it requires the `jupyterlab-plotly` extension to be installed which is responsible for the rendering of the graphs/plots. I followed the steps under the "JupyterLab Support" section in the getting started guide [here](https://plotly.com/python/getting-started/) and was able to render the graphs in my local Jupyter Lab as follows:

![Screenshot from 2021-04-21 15-24-37](https://user-images.githubusercontent.com/7343099/115610809-598c1680-a2b7-11eb-9f5b-538a89be0b5b.png)

The main requirements would be:

1. [Node](https://nodejs.org/) needs to be installed
2. `jupyterlab` and `ipywidgets` packages would need to be installed
3. The `jupyterlab-plotly` and `jupyter-widgets` (optional) extensions need to be installed

**Comment by MichaelClifford** [comment]
There is also the [ipympl](https://github.com/matplotlib/ipympl) package that provides some basic interactivity. But it also looks like it has to be installed in the image before starting.

**Comment by MichaelClifford** [comment]
@chauhankaranraj @aakankshaduggal @isabelizimm 

The above comments seems to indicate 2 problems. 1) the current jupyter lab images don't contain the sufficient dependencies to support interactive visualization. 2) The tool we use to visualize our work becomes dependent on the images we use. i.e if we develop this in a Jupyter lab environment then it will break in a jupyter notebook environment.

This is starting to sound like good reasons to do visualizations outside of jupyter in dedicated dashboarding tools :smile:

As far as issue 1) let's fold this into what @hemajv is working on in #218 and decide what tools we would like to standardize on and request they be included in the base Jupyterlab image. 

As far as issue 2) I'm not exactly sure how to handle this one right now other then moving away from JH completely for this type of work, which I'm not sure if that is the right approach either. 

In either case, it sounds like this issue is blocked on the "interactive" element. Can we shift gears here a bit and just read and display the collected KPI's using seaborn for now? WDYT?

**Comment by hemajv** [comment]
Yes, I think there are a lot of issues that we discovered in #238 when trying to integrate interactive graphs in jupyter notebooks with Gatsby. Currently, there is no Gatsby support for rendering interactive plotly graphs in jupyter notebooks and I think for now we will be using `seaborn` + `ipywidgets` to create basic visualizations within the notebook (making it easier to render on our opf website)

**Comment by chauhankaranraj** [comment]
> I think for now we will be using `seaborn` + `ipywidgets`

Hey team, so the `ipywidgets` are not rendering on jupyterlab correctly, even after enabling the `jupyterlab_widgets` extension that comes pre-loaded in the elyra notebook image. Anyone know of a workaround for this?

I think this odh upstream issue related to this problem opendatahub-io/s2i-lab-elyra#32

/cc @MichaelClifford @oindrillac @hemajv @aakankshaduggal @Shreyanand @isabelizimm
