### ISSUE TITLE
Determine if Superset can work with new public bucket

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#219]
Creating a connection between Ceph, Hue and Superset has not been working. However, we have a new added a new public bucket and updated the cluster since we last tried to use these tools. Test Superset again and see if we can connect to s3. 

#123 

**Acceptance Criteria** 

- [ ] Determination if Superset can work with new public bucket

**Comment by pacospace** [comment]
cc @xtuchyna and issues to refer from Operate First: https://github.com/operate-first/support/issues/183, https://github.com/operate-first/support/issues/184

**Comment by MichaelClifford** [comment]
New bucket did not seem to address this issue : ( continue to get the following error:
`org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:com.amazonaws.AmazonClientException: Unable to execute HTTP request: test-public-bucket-596bc441-3be5-42e7-a82c-49736fa8b42a.s3.openshift-storage.svc: Name or service not known);`
