### ISSUE TITLE
Initial EDA on google cloud storage log data.

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#22]
There is a fair amount of semi-structured log (text) data that gets generated by the CI process. There are likely valuable insights in this data that could be leveraged by SME's if there was an automated way of reducing the total amount of logs that had to be reviewed. As a data scientist, I would like to understand the nature of this data and how best to access it in a data science friendly format, so that I can contribute to the development of automated ML methods for analyzing it. 

Acceptance Criteria:
- EDA notebook for log data found [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/)

**Comment by oindrillac** [comment]
This looks complete can this be closed? @codificat

**Comment by MichaelClifford** [comment]
This is a rather old issue, and we've done a bit of EDA on the log data since it was originally opened. Closing :)
