### ISSUE TITLE
Short Video of KPI Notebook Contribution

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#233]
Create a short video for the website going over the KPI template notebook meant for contributors who wish to contribute towards the project with a new KPI notebook.

@shreyanand can you create a short video on this? basically a version of what you presented in the team meeting?

**Comment by Shreyanand** [comment]
@oindrillac @MichaelClifford  Hey guys, did the first take, lmk your comments.

[Video](https://drive.google.com/file/d/15tj3ksP0aWN7Hg0L-nBX3jIbb9ouyeGP/view?usp=sharing)

**Comment by Shreyanand** [comment]
[Take 2](https://drive.google.com/file/d/1aLXO7_2RT51BOAn4uTWgJzNgXm7xke2h/view?usp=sharing)

**Comment by MichaelClifford** [comment]
:+1: Nice video: couple of comments:

1) Around minute 4 you introduce the idea of automation, it would be good to include this at the beginning to motivate why we need all these conventions in the first place. Also at the beginning maybe give a quick summary of what you are going to present and why. 
2) For the environment variables section, do you want to mention that you need to supply them by either .env or through the spawner ui?  And that for contributing and developing metrics you can rely purely on the example data, no creds needed, but the automation workflow will take advantage of them? 
3) While discussing ceph communication, do you want to discuss the source of data a bit. So, data is either the example in the repo, you could pull your own, or rely on the historical data in ceph. But in either case, the notebooks you develop should simply process existing data and calculate a metric, they aren't expect to collect any themselves.

**Comment by Shreyanand** [comment]
[Take 3](https://drive.google.com/file/d/1g2yLEJ8nVJB1ylKyTNAGkOZIImOJrxxc/view?usp=sharing)

**Comment by oindrillac** [comment]
Looks good! 👍 @Shreyanand

**Comment by MichaelClifford** [comment]
Looks Good! :ship:

**Comment by oindrillac** [comment]
@Shreyanand can you please also link this to the `/docs/content.md`?

**Comment by Shreyanand** [comment]
@oindrillac Where do you think it'll go best? Should I add a link to the metric template notebook and this video under the test grid section?

**Comment by oindrillac** [comment]
@Shreyanand this could go in both places!
