### ISSUE TITLE
Short Video of Elyra KFP Pipelines

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#234]
Create short video to add to website/blog on how to automate and run notebooks for this project in a pipeline using Kubeflow and Elyra

**Comment by oindrillac** [comment]
currently blocked on #255

**Comment by oindrillac** [comment]
Managed to record one :)
https://drive.google.com/file/d/15IgBxizRQisQdMgBaDv3idfpaPVACjqr/view?usp=sharing
Please take a look @MichaelClifford @Shreyanand

**Comment by MichaelClifford** [comment]
:+1: good video. I have a couple of comments. 

1) Do you want to show launching the image from the spawner UI? You could fast-froward our just cut over the loading. 
2) Can you show the repo url on github, as though you were actually going to clone it. 
3) When discussing the notebooks can you mention that we have a template notebook that outlines all the conventions, and maybe mention that we have another video that goes over it in detail. 
4) Show how you can tag and push a new release by just opening a PR
5) Go through the command line functions a bit slower explaining the parameters. 
6) Maybe want to say something about bucket credentials being public. Or tell folks to ensure they aren't using private keys as they can be exposed on the cluster ? 
7) I don't think you need to walk through the whole utility notebook. You can just have it print the results and confirm that it worked.

**Comment by oindrillac** [comment]
@MichaelClifford thanks for your inputs. Will make those modifications.

**Comment by oindrillac** [comment]
[Here's](https://drive.google.com/file/d/15FQ0qfghVJhFhsLZbphYo_vzEud84WrB/view?usp=sharing) the revised take incorporating the above suggestions. Please take a look :)

**Comment by MichaelClifford** [comment]
:ship: :+1:

**Comment by MichaelClifford** [comment]
@oindrillac good video. Can you upload it and add the link to `/docs/content.md`?

**Comment by oindrillac** [comment]
@MichaelClifford thanks uploaded. PR to link to content : https://github.com/aicoe-aiops/ocp-ci-analysis/pull/269
