### ISSUE TITLE
Video Walkthrough for Telemetry EDA

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/ocp-ci-analysis#235]
Create a short video to add to the website/blog on how to collect relevant Telemetry data for builds/CI runs on test grid and EDA.

**Comment by chauhankaranraj** [comment]
The first draft for this video is available [here](https://drive.google.com/file/d/1HGprttoEN5DJhpNC9_m8Kvxgmbxcl7ZD/view?usp=sharing).

**Comment by MichaelClifford** [comment]
:ship:  Good job!
