### ISSUE TITLE
Data Viz: Assess Plotly Dash

### ISSUE THREAD

**Issue by hemajv** [aicoe-aiops/ocp-ci-analysis#238]
In https://github.com/aicoe-aiops/ocp-ci-analysis/issues/218, we evaluated potential alternatives to Superset and identified favorable tools/python libraries suitable for our data visualization needs. Among them, [Plotly](https://plotly.com/) seems to be a useful python library which can be easily integrated within jupyter notebooks for creating interactive visualizations and we are also exploring this in https://github.com/aicoe-aiops/ocp-ci-analysis/issues/217. The plotly charts rendered can also be consolidated into a dashboard like manner using Dash, which is a web application for displaying the visualizations.

**Acceptance Criteria:**

- [X] Identifying all the necessary dependencies required to have Plotly setup in JupyterHub/JupyterLab
- [X] Running a Dash app for rendering Plotly graphs and see if its feasible to use
- [ ] Integration with Gatsby for rendering the visualizations on operate-first website

**Comment by hemajv** [comment]
**Update**: Plotly integration with Gatsby doesn't seem as easy and straight-forward. It does not seem to be "officially" supported, but there are workarounds which people have tried and managed to render the plotly charts. Tried out few workarounds, but haven't been successful yet. Created an upstream [issue](https://github.com/gatsbyjs/gatsby/issues/31125) and [discussion](https://github.com/gatsbyjs/gatsby/discussions/31126) to seek further help from the Gatsby community. Continuing to look into trying some other workarounds to see if we can get it to work before we completely rule out using plotly. But I think the more we dig into these "jupyter integrated" viz tools, the more likely we see the need for choosing a standalone visualization tool instead.

**Comment by oindrillac** [comment]
I think the problem is also firstly something to do with how the notebook is being converted to HTML. Right now, we are using a package (@rafaelquintanilha/gatsby-transformer-ipynb) that doesn't support converting the plotly plot into an interactive html plot or an image. But it does support converting image outputs into it's respective html version. When I looked into how a common package which does the same - nbconvert (to convert jupyternotebooks into html, pdf etc) was run on the notebook file, even that failed to generate the plotly plot. Which is a step forward in the understanding that there might not be support yet to convert plotly interactive plots in jupyternotebooks to an html interactive version of that.

**Comment by hemajv** [comment]
> I think the problem is also firstly something to do with how the notebook is being converted to HTML. Right now, we are using a package (@rafaelquintanilha/gatsby-transformer-ipynb) that doesn't support converting the plotly plot into an interactive html plot or an image. But it does support converting image outputs into it's respective html version. When I looked into how a common package which does the same - nbconvert (to convert jupyternotebooks into html, pdf etc) was run on the notebook file, even that failed to generate the plotly plot. Which is a step forward in the understanding that there might not be support yet to convert plotly interactive plots in jupyternotebooks to an html interactive version of that.

Yes, exactly. After looking into/trying the workarounds mentioned [here](https://elcess.us/Integrating-Plotly-with-Gatsby/) and [here](https://janosh.dev/blog/gatsby-interactive-plots), it seems like currently the plotly graphs can only be rendered within the standalone HTML pages, but there is no support for rendering it within the notebook itself.

Moving forward, I think we should consider using `seaborn` along with `ipywidgets` for basic visualizations within our notebooks (which @chauhankaranraj @aakankshaduggal and @isabelizimm are working on in #217) so that they can easily be rendered in our opf website and use a dedicated visualization tool (like Superset or Redash etc) for more advanced interactive visualizations instead.

thoughts? @MichaelClifford @oindrillac @Shreyanand @aakankshaduggal @chauhankaranraj @isabelizimm

**Comment by chauhankaranraj** [comment]
> Yes, exactly. After looking into/trying the workarounds mentioned [here](https://elcess.us/Integrating-Plotly-with-Gatsby/) and [here](https://janosh.dev/blog/gatsby-interactive-plots), it seems like currently the plotly graphs can only be rendered within the standalone HTML pages, but there is no support for rendering it within the notebook itself.

Hm is there a strong reason why we want the graphs within a notebook? What if we embed just the graphs (e.g. in an iframe) on a page on the opf website?

**Comment by MichaelClifford** [comment]
> Moving forward, I think we should consider using seaborn along with ipywidgets for basic visualizations within our notebooks

This sounds like a good solution for the immediate future : ) Let's do it!

@hemajv what if we relaxed the constrain on this being rendered with gatsby? If we only cared about our notebook images, is plotly (and dash) in jupyter lab a good solution for us?     

> If our goal is to have KPI visualizations, then what if we embed just the graphs (e.g. in an iframe) on a page on the opf website?

@chauhankaranraj, good suggestion ; ) but our goal is also to develop a nice workflow for others to model and identify where there are gaps in our current tooling. So although iframes in a standalone HTML page on the site might work, I'm not sure we could justify presenting it that way.

**Comment by hemajv** [comment]
After trying to replicate the setup [here](https://github.com/vpavlin/dash-openshift) and [here](https://github.com/anudhag/dash-openshift), for running a Dash app to render plotly graphs, it seems like there are still some additional overhead that will be required for us to maintain and use a Dash app. Rather, it would be easier to use a standalone visualization tool like Superset which has an end-end capability for scaling, collaborating, creating and sharing dashboards among our team.

The final assesment of Plotly Dash is that its a great visualization tool, however the main drawbacks are:

1. Lack of Gatsby support for rendering the Plotly graphs within our notebooks
2. Open source version of Dash does not allow us to scale, have additional users, create and manage dashboards. It just runs as a web framework (built on top of Flask) and serves the purpose of rendering the interactive plotly graphs.

This highlights the need for a standalone viz tool to support all other interactive visualization needs and using python library like `seaborn` for creating simple visualizations in our notebook (which we have covered in #217). The IDH team is also focusing on prioritizing Superset to be available and replacing Thrift server with Trino (being discussed [here](https://github.com/operate-first/support/issues/119)) and pushing to test this out in our opf environment. So we should be able to have Superset working soon! :crossed_fingers:
