### ISSUE TITLE
AttributeError: module 'black' has no attribute 'PY36_VERSIONS'

### ISSUE THREAD

**Issue by harshad16** [aicoe-aiops/ocp-ci-analysis#246]
`AttributeError: module 'black' has no attribute 'PY36_VERSIONS'` does anyone know why aicoe-ci/prow/pre-commit test is throwing this error? The pre-commit runs without issue on the jupyterlab v7 image. 

_Originally posted by @MichaelClifford in https://github.com/aicoe-aiops/ocp-ci-analysis/issues/199#issuecomment-827072810_

**Comment by harshad16** [comment]
Found the source of the issue.
the newer version of black has removed the support for 'PY36_VERSIONS' attribute.
```
(app-root) pip install black==21.4b0
...
(app-root) python
Python 3.8.3 (default, Aug 18 2020, 08:56:04) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import black
>>> black.PY36_VERSIONS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'black' has no attribute 'PY36_VERSIONS'
```
as earlier black_nb componenet used to use the previson version of black, there was no issue.
```
(app-root) pip install black==20.8b1
...
(app-root) python
Python 3.8.3 (default, Aug 18 2020, 08:56:04) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import black
>>> black.PY36_VERSIONS
{<TargetVersion.PY36: 6>, <TargetVersion.PY38: 8>, <TargetVersion.PY37: 7>}
```

the issue is in black_nb upstream.
https://github.com/tomcatling/black-nb/blob/74b5e0ce48d4395d33c4bfa51dcab142ea3b9d35/setup.py#L37

**Comment by harshad16** [comment]
We have few possible options:
1. Wait for the fix to be done upstream and we update the pre-commit config. (proper fix)
2. use a forked solution (Hack)
```
  - repo: https://github.com/harshad16/black-nb
    rev: '0.4.1'
    hooks:
      - id: black-nb
```
3. disable the black-nb hook from pre-commit (quick fix)
https://github.com/aicoe-aiops/ocp-ci-analysis/blob/d907c430941b55e9fd1cdefdbe5957a0fa059687/.pre-commit-config.yaml#L49

@MichaelClifford

**Comment by MichaelClifford** [comment]
@harshad16 
1. I think using the forked solution until the upstream fix is made is probably the best way to go. WDYT?
2. Is this issue only affecting this repo? If so, what about our dependencies is breaking it? Or is this an issue that will impact all our repos now?

**Comment by harshad16** [comment]
> 1. I think using the forked solution until the upstream fix is made is probably the best way to go. WDYT?

Sounds good.
I will open a pr for the forked solution
I have submitted a solution upstream as well for quick results, let's see.

> 2. Is this issue only affecting this repo? If so, what about our dependencies is breaking it? Or is this an issue that will impact all our repos now?

i only know of this repository using this.  (will check on others)
dependencies of our repository is not breaking it, it the dependency of the check we are using.
it will impact any repo using black_nb pre-commit.
