### ISSUE TITLE
Different Default Datasets in KPI notebooks

### ISSUE THREAD

**Issue by chauhankaranraj** [aicoe-aiops/ocp-ci-analysis#249]
Hey team,

Is there a particular reason for using [testgrid_810](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/b4b9d6a09a438af4c5bf585cb6d47383f826cb75/data/raw/testgrid_810.json.gz) as the default dataset (for non-automated runs) in [`number_of_flakes`](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/b4b9d6a09a438af4c5bf585cb6d47383f826cb75/notebooks/data-sources/TestGrid/metrics/number_of_flakes.ipynb) and [`correlated_failures`](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/b4b9d6a09a438af4c5bf585cb6d47383f826cb75/notebooks/data-sources/TestGrid/metrics/correlated_failures.ipynb) notebooks? The rest of the metric notebooks seem to be using [testgrid_183](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/b4b9d6a09a438af4c5bf585cb6d47383f826cb75/data/raw/testgrid_183.json.gz).

Would it make sense to have all notebooks use the same default, so that locally run KPI calculations are more consistent? wdyt?

**Comment by MichaelClifford** [comment]
:+1: @chauhankaranraj  Sounds good yes, lets remove "810" I think that was the original dataset I pulled before 183. Let's have only one.
