### ISSUE TITLE
Video walkthrough of Bugzilla EDA

### ISSUE THREAD

**Issue by hemajv** [aicoe-aiops/ocp-ci-analysis#250]
Create a short video to add to the website/blog on how to collect relevant Bugzilla data for CI tests on test grid and EDA.

**Comment by chauhankaranraj** [comment]
Hey all the first draft of the video is [here](https://drive.google.com/file/d/1nAcXiTWTziwTjQX3ersVTHoS2JMKBTg6/view?usp=sharing). Let us know what you think! :)

**Comment by isabelizimm** [comment]
Looks great!

**Comment by oindrillac** [comment]
Looks good ! 👍🚢

**Comment by MichaelClifford** [comment]
Good Job! Just one comment. 

I don't think we need the part at the beginning where we discuss our investigation and how we figured out how to do it. Can we edit that part out? ~1:12 to ~2:11. I think we can just discuss the motivations for doing this and the data sources we collect from. WDYT?

**Comment by chauhankaranraj** [comment]
> Can we edit that part out? ~1:12 to ~2:11.

Sure, here's the [updated video](https://drive.google.com/file/d/1Ij-CRG67BLEPPp2HVYYXkO2CpIOR-Iix/view?usp=sharing)
