### ISSUE TITLE
Unable to assign people/projects to issues

### ISSUE THREAD

**Issue by isabelizimm** [aicoe-aiops/ocp-ci-analysis#259]
**Description**
As a contributor to the `ocp-ci-analysis` repo, I would want access to assign myself and others to issues and add issues to project boards.

I believe I need added to https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/OWNERS as a reviewer (?), but not certain this is the correct fix. 

cc: @MichaelClifford

**Comment by tumido** [comment]
@isabelizimm I think this is beyond repo permissions (the projects are on the organization scope). I'll check out what's the setting there and if you're not missing a team assignment.

**Comment by tumido** [comment]
@isabelizimm I've changed permissions for the [team-aiops](https://github.com/orgs/aicoe-aiops/teams/team-aiops). All members should be able to `triage` on all repos in this org now. If it still doesn't work, just ping me :slightly_smiling_face:

**Comment by isabelizimm** [comment]
that seems to have worked :) thank you!
