### ISSUE TITLE
Short Video on GitHub data notebook

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#268]
Create a short video that walks users through `notebooks/data-sources/oc-github-repo/github_PR_EDA.ipynb`

Acceptance criteria:

- [x] post video to youtube
- [ ] link video on content page

**Comment by MichaelClifford** [comment]
@oindrillac @Shreyanand @chauhankaranraj @aakankshaduggal @isabelizimm @hemajv 

Please review my first attempt at a content video [here](https://drive.google.com/file/d/1Uu308r_Jcul8svjHmqUfq8GZx3GG6xXF/view?usp=sharing). 

Any feedback would be much appreciated : )

**Comment by oindrillac** [comment]
@MichaelClifford went over it. nice video 👍 🚢

**Comment by oindrillac** [comment]
anybody else willing to give another set of eyes before we :ship: it? :slightly_smiling_face: 
@aakankshaduggal @chauhankaranraj @Shreyanand @hemajv @isabelizimm

**Comment by aakankshaduggal** [comment]
The video looks good @MichaelClifford :rocket:

**Comment by isabelizimm** [comment]
Looks good! If you're not planning to re-record, I think it's great as-is. If you're planning to re-record anyway, it might be helpful to say in 1 or 2 lines what "meaningful interaction" (around timestamp 7:21) would look like if it did exist. Definitely not necessary, but might help a non-data scientist persona understand the graph.

**Comment by chauhankaranraj** [comment]
> anybody else willing to give another set of eyes before we  it? 
> @aakankshaduggal @chauhankaranraj @Shreyanand @hemajv @isabelizimm

/lgtm :rocket:

**Comment by hemajv** [comment]
The video looks good! :ship:

**Comment by MichaelClifford** [comment]
Thanks for the comments all! 

Video posted to youtube:  https://youtu.be/bUm0jvXaY14
