### ISSUE TITLE
Short Video on prow data 

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#271]
Create a short video that walks users through `notebooks/data-sources/gcsweb-ci/prow_archive_discovery.ipynb`

Acceptance criteria:

- [x] post video to youtube
- [ ] link video on content page

**Comment by Shreyanand** [comment]
[Take 1](https://drive.google.com/file/d/19uuKbfVqs-FofQ5gFo3v1XayLId53JGN/view?usp=sharing) Please let me know the comments!

**Comment by MichaelClifford** [comment]
:+1: Good video !

**Comment by Shreyanand** [comment]
[Youtube link](https://youtu.be/JjFWFaMfUJA)

For the second acceptance criteria, do you mean [here](https://www.operate-first.cloud/data-science/ocp-ci-analysis/notebooks/data-sources/gcsweb-ci/prow_archive_discovery.ipynb)?

**Comment by MichaelClifford** [comment]
@Shreyanand 
Here: docs/content.md#prowgcs-artifacts
