### ISSUE TITLE
Restructure the Visualization Notebook

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/ocp-ci-analysis#275]
We would want to restructure the visualization notebook so that it's easier for the end-user to understand the notebooks better.

Acceptance Criteria :
- [x] Polish the notebook.
- [x] Divide the notebook into a series of notebooks.

**Comment by isabelizimm** [comment]
Bringing our earlier discussion here: how are we thinking of dividing notebooks? We had mentioned different visualizations for different personas. WDYT?

**Comment by MichaelClifford** [comment]
Good Summary @hemajv :smile:  

Here is my idea for simplifying the visualizations. 

1. All visualizations are aggregated to the highest platform level. So there is no selection of tabs, or grids or anything. For example for "# of timed out test" it would be the number of all timed out tests for all grids as reflected in `blocked_timed_out-2021-4-14.parquet`. Do this for every file in the `blocked_timed_out` directory to get one value for each day, then plot these values as a time series. **Every plot should just be a time series** showing the change in values from day to day. (Except for correlated failures, lets ignore that one for now)   

2. Let's forget the personas stuff for the time being (until we have a real dashboarding tool)

3. As far as subdividing the notebooks, I thought we could do it thematically, like between test metrics, build metrics, etc. but I think this will lead to like 1 notebook having 15 metrics and 1 having 4. That said, if we implement 1. a notebook that just has 15 plots giving a high level summary of the test grid activity, it might not be too long.    


@hemajv @aakankshaduggal @isabelizimm @chauhankaranraj @Shreyanand WDYT? Happy to discuss this further : )

**Comment by chauhankaranraj** [comment]
> 1. All visualizations are aggregated to the highest platform level. So there is no selection of tabs, or grids or anything. For example for "# of timed out test" it would be the number of all timed out tests for all grids as reflected in `blocked_timed_out-2021-4-14.parquet`. Do this for every file in the `blocked_timed_out` directory to get one value for each day, then plot these values as a time series. **Every plot should just be a time series** showing the change in values from day to day. (Except for correlated failures, lets ignore that one for now)

This seems reasonable to me :smile: 

Lets update the acceptance criteria for #217 to have just one notebook with ~15 total graphs (1 time series graph per metric)? 
And defer the "in-deph" and "sliced and diced by tabs, grids, etc" graphs to a separate issue (for which we could clean up and use the notebook we already have in #257)?

wdyt?

**Comment by MichaelClifford** [comment]
@chauhankaranraj updated the acceptance criteria for #217

**Comment by MichaelClifford** [comment]
:+1:
