### ISSUE TITLE
EDA into distribution of time taken to merge. 

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#279]
As a data scientist trying to predict the time to merge of a PR, it is important to determine how to best phrase the machine learning problem, and narrow down on what we are planning to predict.

We need to explore the current distribution of time taken to merge to evaluate whether we can break down the time taken to merge into reasonable chunks.

This will help frame the Machine Learning problem eg Classification/Regression.

Acceptance Criteria
- [ ] Notebook to explore the time to merge distribution for past PRs and determine whether time to merge could be broken down into reasonable chunks.

**Comment by MichaelClifford** [comment]
@oindrillac It might make sense to include this as part of `notebooks/data-sources/oc-github-repo/github_PR_EDA.ipynb` instead of creating a completely new notebook. WDYT?

**Comment by oindrillac** [comment]
@MichaelClifford yes, this would be good extension to the notebook 👍
