### ISSUE TITLE
Identify and engineer possible features for time to merge ML problem

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#280]
As a data scientist trying to predict the time to merge of a PR, we want to explore all available columns from PR data in detail and come up with possible features.

Acceptance Criteria
- [ ] Explore all available columns in PR data which have not been explored in detail so far, eg: reviews, interactions, labels.
- [ ] Engineer features from available columns and create a dataset with possible feature columns.

**Comment by MichaelClifford** [comment]
I think working with what we have at the moment is a good idea. But if you eventually come to the conclusion that more PR info is needed, you can reach out to @xtuchyna about adding more features.  

Do you plan on having this as a separate notebook or an extension of the original EDA?

**Comment by oindrillac** [comment]
@MichaelClifford yes, I think we can start with the columns we have available to us and explore them to transform them into meaningful features. 

For example the `Created_at` timestamp field can be transformed to create some possibly meaningful categorical features like:
`day_of_week`, `day_of_month`, `month_in_year`, `time_of_day`

This could also be an extension of the initial EDA notebook.

**Comment by MichaelClifford** [comment]
@oindrillac :+1: Cool. And again yes, I think making it an extension of the EDA notebook make sense. We _may_ eventually want to have a separate feature engineering notebook to serve as a pipeline step, but I don't think that's necessary just yet.
