### ISSUE TITLE
KPI Request : Probability to Fail

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/ocp-ci-analysis#282]
As an OpenShift manager, I would want to know for a given moment in time, what is the probability that the test will fail. Using this information, we plan to build a model that uses the probability to fail to predict the time to failure. (#226 )

Acceptance Criteria : 
- [ ] small notebook in `notebooks/data-sources/TestGrid/metrics/` that collects this metric and stores it as a csv
- [ ] The metric should store `probability-to-fail`.

Approach : 
For a test (or set of tests), look at the distribution of test duration for all failed tests and the distribution of test duration for all the successful tests (ideally generating two distinct distributions). Then given a new duration value, evaluate the likelihood that it belongs to one of the two distributions. This will give a way to calculate the "probability to fail" based solely on the duration metric.

**Comment by aakankshaduggal** [comment]
This metric is dependent on the "test_duration" value to calculate the probability to fail. However, we have the test_duration value well populate for the test "Overall" but for all the other tests, earlier it was empty : screenshot from test_pass_failures.ipynb - 
![image](https://user-images.githubusercontent.com/26301643/122092369-d7603000-cdd7-11eb-87c0-a95529d33315.png)

And now, when I get the data directly from `/data/raw/testgrid_183.json.gz`, the value for all tests other than "Overall" is same. :

![image](https://user-images.githubusercontent.com/26301643/122092538-0a0a2880-cdd8-11eb-8a5c-f8cd2316e4d1.png)


In my opinion, we should get the "test_duration" value again to ensure there are no discrepancies. Any suggestions/leads are appreciated.

cc: @hemajv , @MichaelClifford , @chauhankaranraj , @oindrillac , @Shreyanand , @isabelizimm

**Comment by oindrillac** [comment]
> This metric is dependent on the "test_duration" value to calculate the probability to fail. However, we have the test_duration value well populate for the test "Overall" but for all the other tests, earlier it was empty : screenshot from test_pass_failures.ipynb -
> ![image](https://user-images.githubusercontent.com/26301643/122092369-d7603000-cdd7-11eb-87c0-a95529d33315.png)

@aakankshaduggal IIRC, it was designed to fetch only for the test "Overall" since it had empty values for other tests.

> And now, when I get the data directly from `/data/raw/testgrid_183.json.gz`, the value for all tests other than "Overall" is same. :
> 
> ![image](https://user-images.githubusercontent.com/26301643/122092538-0a0a2880-cdd8-11eb-8a5c-f8cd2316e4d1.png)
> 
> In my opinion, we should get the "test_duration" value again to ensure there are no discrepancies. Any suggestions/leads are appreciated.
> 
> cc: @hemajv , @MichaelClifford , @chauhankaranraj , @oindrillac , @Shreyanand , @isabelizimm

Does the discrepancy exist for the datasets stored on s3 as well? or do you see it being populated only for the `testgrid_183.json`? 

Based on the data available, can we tune this problem to determine the probability of a set of tests to fail? For labels, you can use the Overall Pass/Fail label.

**Comment by MichaelClifford** [comment]
Duration for individual tests within a job does exist on TestGrid, see image below.  I think our current metric was focused on build duration which is represented by the "overall" label. 

![image](https://user-images.githubusercontent.com/4494906/122095480-6e7ab700-cddb-11eb-9a7d-b7046328500e.png)

@aakankshaduggal If you need extra data for this metric can you open an issue and update `notebooks/data-sources/TestGrid/metrics/time_to_test.ipynb` to collect the additional data? :smile:

**Comment by oindrillac** [comment]
The time duration for individual tests is recorded in a very erratic manner. 
for example see below, it is logged for some tests and not for others

![image](https://user-images.githubusercontent.com/32435206/122097275-7e939600-cddd-11eb-9028-860eaa71d2a8.png)

Even for many tests where they are logged, time duration values do not exist for every timestamp and this could result in some inconsistent data.

![image](https://user-images.githubusercontent.com/32435206/122097385-9ff48200-cddd-11eb-8ec4-d66a732aa0fe.png)

**Comment by aakankshaduggal** [comment]
>Even for many tests where they are logged, time duration values do not exist for every timestamp and this could result in some inconsistent data.

Exactly what I was pointing at @oindrillac. Thanks for the explanation. But in order to collect the optimal stopping point, this looks like an important metric to be tracked. 

> @aakankshaduggal If you need extra data for this metric can you open an issue and update notebooks/data-sources/TestGrid/metrics/time_to_test.ipynb to collect the additional data? 

@MichaelClifford I was gonna create one, but I thought we can discuss here and then proceed with that :smile:
