### ISSUE TITLE
Possible duplication in KPI data being saved

### ISSUE THREAD

**Issue by chauhankaranraj** [aicoe-aiops/ocp-ci-analysis#291]
**Describe the bug**
While working on the visualization notebook, I noticed that the `test_duration` metric appears as a column in 4 different KPI files - `build_pass_failure`, `number_of_flakes`, `test_pass_failures`, and `time_to_test`. Is there any value in saving this metric in all of these parquets? Or is it redundant and can be tracked in just one of them, maybe `time_to_test`? 

**To Reproduce**
1. Download parquets from any date located under these prefixes - `build_pass_failure`, `number_of_flakes`, `test_pass_failures`, and `time_to_test` 
2. Open the parquet files and inspect the columns

**Expected behavior**
**_If_** there is no additional value in saving the test duration metric in multiple KPI files, then it should be stored only in one of them and removed from the others.

**Additional context**
Some of the KPI files are quite large when read into memory so maybe removing redundant columns might help a bit?

**Comment by oindrillac** [comment]
I think its a good idea to modify where we are reading the dataframe in the notebooks to drop that column
```
# Convert to dataframe
df = pd.DataFrame(
    unrolled_list,
    columns=["timestamp", "tab", "grid", "test", "test_duration", "flake"],
)
``` 
if we need the test duration value in the future to draw correlations between a particular metric eg: flake and test duration, we can always join on multiple metric datasets.

**Comment by chauhankaranraj** [comment]
> I think its a good idea to modify where we are reading the dataframe in the notebooks to drop that column

Yep, that's what I was thinking too, but wanted to ask others if there was any particular reason for keeping that metric column in different files

**Comment by MichaelClifford** [comment]
Good catch @chauhankaranraj Lets try and reduce data duplication as much as possible and fix this issue. Lets drop this from all other files except for `time_to_test`
