### ISSUE TITLE
Video Walkthrough of Failure Classification notebook

### ISSUE THREAD

**Issue by isabelizimm** [aicoe-aiops/ocp-ci-analysis#292]
Short video highlighting the work shown in [notebook](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/failure-type-classification/failure_type_classifier.ipynb)

**Comment by isabelizimm** [comment]
Rough draft of video [here](https://drive.google.com/file/d/1JKIkFQlmgcqgKdrOXketGiaRX5znXPjN/view?usp=sharing)

Questions/comments/concerns? : ) 
@aakankshaduggal @MichaelClifford @chauhankaranraj @oindrillac @hemajv

**Comment by MichaelClifford** [comment]
lgtm : )

**Comment by aakankshaduggal** [comment]
Looks good :+1:

**Comment by hemajv** [comment]
video looks great! nice work @isabelizimm @Shreyanand :clap:

**Comment by isabelizimm** [comment]
Available on the Operate First YouTube!

https://www.youtube.com/watch?v=BKnF174eZN0

**Comment by chauhankaranraj** [comment]
> Questions/comments/concerns? : )
> @aakankshaduggal @MichaelClifford @chauhankaranraj @oindrillac @hemajv

Sorry for the delay in review, looks like it got merged while I was waching it :sweat_smile: But ig for the sake of my clarity, I'll leave my comment anyway.

It seems like the definitions of "install flake" are a bit inconsistent in the first part vs the second part. At ~1:27, it's being defined as "rows with solid red chunks with white to the right". Then at ~6:30 it's being defined as "if >90% tests are not run for 2 or more consecutive days".

If these could be made more consistent that'd be awesome! But otherwise looks great :smile:

**Comment by isabelizimm** [comment]
> > Questions/comments/concerns? : )
> > @aakankshaduggal @MichaelClifford @chauhankaranraj @oindrillac @hemajv
> 
> Sincere apologies for the delay in review, looks like it got merged while I was waching it  But ig for the sake of my clarity, I'll leave my comment anyway.
> 

Oh no! Sorry I got too excited to post :) 

> It seems like the definitions of "install flake" are a bit inconsistent in the first part vs the second part. At ~1:27, it's being defined as "rows with solid red chunks with white to the right". Then at ~6:30 it's being defined as "if >90% tests are not run for 2 or more consecutive days".
> 
> If these could be made more consistent that'd be awesome! But otherwise looks great

Good catch-- I don't know if those are _fully_ inconsistent (although they could be). In the image, the test failed (red) and then was not run (white). The function that detects install flakes is focusing on the "not run" part of the install flake to differentiate from different types of flakes. 

It's subtle but apparent, so now I'm debating if it's different/unclear enough to 1) make an edit to video and repost 2) add a popup note in the video to clarify 3) add a * in the description explaining further. Or do all or none of these things, or something different. WDYT?

**Comment by MichaelClifford** [comment]
@isabelizimm how much work would it take to create a little pop-up to make the correction?

**Comment by chauhankaranraj** [comment]
> 2) add a popup note in the video to clarify 3) add a * in the description explaining further

Both of these sound like good options to me :+1:

**Comment by Shreyanand** [comment]
@chauhankaranraj Thanks for the catch! The Readme of the project seems to be inconsistent as well. Install flakes should just be defined as vertical white lines (and therefore >90% tests not running for 2 days heuristic) ([Source](https://github.com/aicoe-aiops/ocp-ci-analysis/issues/1)). Will change it soon :+1:
