### ISSUE TITLE
Video walk through of KPI viz nb

### ISSUE THREAD

**Issue by hemajv** [aicoe-aiops/ocp-ci-analysis#299]
Short demo walk through of the simple KPI metric visualization [notebook](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/data-sources/TestGrid/metrics/metric_visualization_generic.ipynb)

**Comment by hemajv** [comment]
initial draft ready for review [here](https://drive.google.com/file/d/1QXga7v4WfNTGHIa-B79DG8i_ViN9CBhx/view?usp=sharing)
@aakankshaduggal @chauhankaranraj @isabelizimm @Shreyanand @oindrillac @MichaelClifford

**Comment by MichaelClifford** [comment]
Good job @hemajv Please post this to the opf youtube channel : )

**Comment by hemajv** [comment]
Uploaded to our YT channel [here](https://www.youtube.com/watch?v=SqGfbyEuZLE&list=PL8VBRDTElCWoGwMhCp04rQFMcIhshv33U&index=11&t=8s)
