### ISSUE TITLE
Missing commit ID's for Openshift testgrids

### ISSUE THREAD

**Issue by SankBad** [aicoe-aiops/ocp-ci-analysis#30]
For testgrid of k8s, we have commit ID's for each run. Marked in the red circle image below:
![imageedit_20_4566214468](https://user-images.githubusercontent.com/29823086/98019357-a3e40e80-1dcf-11eb-950f-aba74a71725c.png)

But for testgrid of Openshift, we don't have commit ID's. Marked in the red circle in the image below:
![imageedit_24_3846326751](https://user-images.githubusercontent.com/29823086/98019939-6469f200-1dd0-11eb-8aeb-5a0371afee3f.png)

We can collect a lot of metadata if we have commit ID available for each run. From those Commit IDs we can create different features that might be used for the data analysis part. Some of those features are
1) What type of file is changed in a commit? because Test cases that fail due to changes in config files are very likely to be flaky
2) A test case that has failed on a git revision that changed a file which was previously changed by more than two authors recently is highly likely to be a real failure
3) A test case that has failed on a git revision where many source code files were changed, is highly likely to be a real failure.

Acceptance criteria: 

- [ ] Communication with an appropriate team to include commit IDs in test grid.

**Comment by SankBad** [comment]
Hi @durandom @MichaelClifford , 

Can we direct this issue to the appropriate team?

**Comment by durandom** [comment]
@SankBad then do the work with the k8s test grids. 
If the results are valuable, we can certainly convince the openshift team to do this.

**Comment by SankBad** [comment]
Sounds good :+1:

**Comment by SankBad** [comment]
I just noticed that for some openshift's testgrids, we have commit id's 
for example: https://testgrid.k8s.io/redhat-openshift-ocp-release-4.3-informing#release-openshift-ocp-e2e-aws-scaleup-rhel7-4.3&sort-by-flakiness=

**Comment by SankBad** [comment]
As we have commit ids for some of the openshift testgrids. I am closing this issue.
