### ISSUE TITLE
Review Sippy Analysis Output 

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#32]
As a data scientist I want to list what analysis output is generated by Sippy to determine if it could be recreated in a notebook environment. 

Acceptance Criteria: 

- [x] Jupyter Notebook that recreates values generated by Sippy or an explanation why it can't be done.

**Comment by martinpovolny** [comment]
15 interesting KPIs here: https://testsigma.com/blog/what-are-the-kpis-of-software-testing-and-qa-testsigma/
