### ISSUE TITLE
Build an OLS Regression Model to predict time to failure

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/ocp-ci-analysis#330]
Sub issue for ML Request : #226 

In order to predict an optimal stopping point, beyond which a test is likely to fail we have used `test_duration` to calculate `probability_to_fail` and now we aim to predict the `time unit failure` i.e. how many days, weeks, months, hours, minutes or seconds do you have until the test in question stops working using an OLS regression model.

**Comment by hemajv** [comment]
Based on a blog post we found [here](https://medium.com/swlh/converting-a-probability-to-fail-into-a-time-to-failure-metric-9a0ddf6122c4), we tried to do an initial pass of training an OLS regression model to predict the time to failure by replicating this code: https://github.com/shadgriffin/phat_to_ttf/blob/master/creating%20time%20to%20failure%20from%20p%20to%20fail.ipynb

You can find the notebook here (section towards the end of the notebook): https://github.com/hemajv/ocp-ci-analysis/blob/mlreq-prob-fail/notebooks/data-sources/TestGrid/metrics/probability_to_fail.ipynb

It seems like the model doesn't perform well with our data set and perhaps we might need additional features to improve the model or consider a different model entirely.

**Comment by aakankshaduggal** [comment]
As per our discussion, we have decided to not move forward with this approach anymore. Is it okay to close this @hemajv @MichaelClifford ?
