### ISSUE TITLE
Timestamp columns show as NULL on Trino 

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/ocp-ci-analysis#344]
In order to visualize the KPI metrics on Superset Dashboard, we are trying to link the metrics data from ceph using cloudbeaver, but however, when we do so the `timestamp` column appears to be `null`. 

We have tried this so far : 
**Approach 1** - converting it into milliseconds format as suggested [here](https://trino.io/docs/current/language/types.html#date-and-timel).

For example, in this dataset, we converted the datetime column to a datetime with milliseconds -
![image](https://user-images.githubusercontent.com/32435206/130276630-56f4110b-3e16-47e1-8070-e1931b6aa93b.png)

When we try to run this query on cloudbeaver -
![image](https://user-images.githubusercontent.com/26301643/130275614-4f0a9aee-3e59-4ead-b411-e28fe3b48389.png)

We see nothing. 

The table run was a `success` 
![image](https://user-images.githubusercontent.com/26301643/130275684-599624ef-3539-4361-a142-b455b2b166da.png)

and this is how the final dataframe on cloudbeaver looks like where "timestamp-ms" shows as NULL datatype-
![image](https://user-images.githubusercontent.com/32435206/130276859-43571b2b-6cec-4502-b889-d745d073b660.png)
**Approach 2** :
The `timestamp` column wasn't datetime64, it was "object". We converted it into datetime64, still gives a null. 

Any other approach/suggestions are welcome.

cc: @oindrillac @hemajv @chauhankaranraj @Shreyanand @isabelizimm @MichaelClifford

**Comment by MichaelClifford** [comment]
Is timestamp a supported data type? did you try just varchar in the table definition?

**Comment by MichaelClifford** [comment]
What kind of object is the "time_stamp" column in the stored dataframe?

**Comment by oindrillac** [comment]
> Is timestamp a supported data type? did you try just varchar in the table definition?

it should be supported https://trino.io/docs/current/language/types.html#timestamp

**Comment by oindrillac** [comment]
> What kind of object is the "time_stamp" column in the stored dataframe?

its currently datetime64

**Comment by MichaelClifford** [comment]
what if you make it a string, then set it as Timestamp on the schema?

**Comment by oindrillac** [comment]
> what if you make it a string, then set it as Timestamp on the schema?


On saving the dataframe `timestamp-ms` column as "str" at `opf-datacatalog/trino-db-str/number_of_flakes`
![image](https://user-images.githubusercontent.com/32435206/130470015-01a34e2d-5af3-44d8-833d-8a060ac9bb9b.png)

the create table runs succesfully
![image](https://user-images.githubusercontent.com/32435206/130470339-d32a4714-fa0a-4cd4-9144-ea4cf1a6fd4f.png)

however, I see nothing when I select rows from the table

![image](https://user-images.githubusercontent.com/32435206/130470489-13f8f4d7-d3a7-4593-a68f-14276ef6c004.png)

**Comment by MichaelClifford** [comment]
One other thing to try. Define it's datatype as varchar for cloudbever schema, then tell superset its your timestamp field. I think that's how we handled it with the earlier implementation.

**Comment by chauhankaranraj** [comment]
It seems like this issue can be resolved by making sure the column names used in the `CREATE TABLE` statement are the same exact as those in the parquet files backing the table. Because by default, hive reads parquet columns by name and not ordinal position (see [docs](https://trino.io/docs/current/connector/hive.html#parquet-format-configuration-properties)). 

So in this particular case, changing `time_stamp` to `timestamp` in the [sql query above](https://user-images.githubusercontent.com/32435206/130470339-d32a4714-fa0a-4cd4-9144-ea4cf1a6fd4f.png) should fix the NULLs.
