### ISSUE TITLE
Collect a fixed train/test/validate data set for TestGrid 

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#35]
As a data scientists, its important to have a fixed immutable dataset to work with while developing, evaluating and validating our initial models. Since the TestGrid data updates everyday, there is potential for poor reproduciblity of experiments if we don't maintain a fixed experimental data set before applying to the live data. 

Acceptance Criteria:

- [x] Maximum available data at date of collection for TestGrid data for Red Hat.

- [x] Stored and accessible in Ceph (or other public hosting)

**Comment by SankBad** [comment]
Hi @MichaelClifford , 

Also, for some models, we might want large datasets. However, I don't have any specific use cases for now.
Are we planning to store data of a certain grid for let's say 10,000 timestamps or more.

**Comment by MichaelClifford** [comment]
The current working dataset for testgrid can be found in this repo under `data/raw/testgrid_810.json.gz` and downloaded directly [here](https://github.com/aicoe-aiops/ocp-ci-analysis/raw/master/data/raw/testgrid_810.json.gz).

I see this as an acceptable solution to this current issue #35, given the small size of the dataset (4.5 mb). But as this project moves forward a more robust data repository should be used. However, that can be addressed in a later issue.
