### ISSUE TITLE
Update time-to-merge model endpoint in inference notebook and documentation

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#414]
The model endpoint in [model_inference.ipynb](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/time-to-merge-prediction/model_inference.ipynb), [model docs](https://github.com/aicoe-aiops/ocp-ci-analysis/tree/master/notebooks/time-to-merge-prediction), [get started docs](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/docs/data-science-get-started.md#interact-with-model-endpoints) for GitHub time-to-merge model still reflects deployment in the zero cluster. We need to update the endpoint to the one deployed in the `ds-ml-workflows-ws` namespace.

**Comment by chauhankaranraj** [comment]
@oindrillac Looks like endpoint got updated in some of the previous README and notebook update PRs, and points to the correct one now. Can we close this?

**Comment by oindrillac** [comment]
yes, this is good to close.
