### ISSUE TITLE
Update GitHub PR TTM Service Deployment

### ISSUE THREAD

**Issue by chauhankaranraj** [aicoe-aiops/ocp-ci-analysis#457]
Currently the GitHub PR time-to-merge prediction [service](http://ttm-pipeline-opf-seldon.apps.zero.massopen.cloud/predict) uses the Seldon server image built from the directory [here](https://github.com/chauhankaranraj/ocp-ci-analysis/tree/5e8fa9eb83d0b428a3b7d90371e19322a65e2a49/models/github-ttm). Now that custom transformers are added through #391, we can add the aforementioned directory to this repo and build image from here instead.

Related to #380, #236

**Acceptance criteria**
- [x] add s2i build directory
- [ ] #459
- [x] update seldon deployment to use this image

**Comment by MichaelClifford** [comment]
@chauhankaranraj can we close this now?

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj can we close this now?

So acceptance criterion 2 (building image using aicoe-ci, instead of manually) is still outstanding, but we do have a separate issue to track it. The other two items are done. What would you suggest we do?

**Comment by MichaelClifford** [comment]
lets split it, close this and move the outstanding to an new issue. : )

**Comment by chauhankaranraj** [comment]
> lets split it, close this and move the outstanding to an new issue. : )

Sounds good!

Acceptance criterion 2 is being tracked in #459
