### ISSUE TITLE
Add GitHub PR Data Insights dashboard to repo

### ISSUE THREAD

**Issue by chauhankaranraj** [aicoe-aiops/ocp-ci-analysis#479]
The [GitHub Repo PR Insights dashboard](https://superset.operate-first.cloud/superset/dashboard/9/) created under the github data EDA / ML request is not currently being tracked via git, and needs to be added to the repo here.

**Acceptance Criteria**
- [ ] add json export of dashboard to repo

**Comment by oindrillac** [comment]
Thanks for remembering! We should add it this time around 🤓

**Comment by chauhankaranraj** [comment]
> Thanks for remembering! We should add it this time around

haha yes :))
