### ISSUE TITLE
Investigate addition of prescription repo to training data for ttm model.

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#497]
Include the prescriptions repo to the list of training repos for the thoth station ttm model and verify whether the model performance is affected. If performance improves, update the model version in the deployment.

**Comment by oindrillac** [comment]
We will remove all the PRs that are created by bots from the training data, if the bots are the major PR contributor I guess including that repo will not have that value.

**Comment by codificat** [comment]
Ah, ok! 
There are contributions by humans as well, so this should be fine - only wanted to point out that there are many more contributions coming from automated "refresh jobs".

**Comment by oindrillac** [comment]
That makes sense. Thanks @codificat!
