### ISSUE TITLE
slight tweaks on readability of initial_EDA.ipynb

### ISSUE THREAD

**Issue by durandom** [aicoe-aiops/ocp-ci-analysis#5]
I dont know how to comment on individual cells in an already committed notebook, so I did it in the PR

https://github.com/aicoe-aiops/ocp-ci-analysis/pull/2#pullrequestreview-475373122

Just some small suggestions, otherwise great notebook I could follow and understand.

**Comment by MichaelClifford** [comment]
Thanks @durandom 

I'll make those changes. : )

**Comment by MichaelClifford** [comment]
@durandom Please see PR #6 It should address the changes you requested.
