### ISSUE TITLE
Short Video Walkthrough of indepth EDA notebook

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#68]
Short Video Walkthrough of in-depth EDA notebook

Acceptance Criteria: 

- [x] Video recorded and signed off by majority of team
- [x] Published to youtube
- [x] Linked on opf site.

**Comment by MichaelClifford** [comment]
Please see this first pass on the indepth EDA notebook walk-through  : ) 
[Video](https://drive.google.com/file/d/13UipP-1Zu5nJKCVx3BcfsvX9qGP8MD0v/view?usp=sharing) 

@Shreyanand @aakankshaduggal @chauhankaranraj @isabelizimm @oindrillac @hemajv

**Comment by MichaelClifford** [comment]
any feedback on the video? @Shreyanand @aakankshaduggal @chauhankaranraj @isabelizimm @oindrillac @hemajv

**Comment by Shreyanand** [comment]
@MichaelClifford Just went through it. Looks great :+1:

**Comment by aakankshaduggal** [comment]
Looks good @MichaelClifford :rocket:

**Comment by chauhankaranraj** [comment]
> any feedback on the video? @Shreyanand @aakankshaduggal @chauhankaranraj @isabelizimm @oindrillac @hemajv

Looks good! :ship:

**Comment by hemajv** [comment]
lgtm! :ship: :+1:

**Comment by MichaelClifford** [comment]
Thanks for the reviews all. see #285 for PR. Here is the published link https://youtu.be/cx2ewhtohn4
