### ISSUE TITLE
Downloading github metadata from commitid's

### ISSUE THREAD

**Issue by SankBad** [aicoe-aiops/ocp-ci-analysis#69]
**Is your feature request related to a problem? Please describe.**
In testgrid, we have commit ids for each run. We want to download the GitHub metadata from these commit ids.

**Acceptance criteria**
Download the following metadata for each commit ids

1. What files are changed in a particular commit
2. Author of the commit
3. For each changed file: How many times that particular file is changed previously. 
4. For each changed file: How many authors edited that particular file.

**Comment by MichaelClifford** [comment]
closing.
Lets consolidate this discussion into issue #108
