### ISSUE TITLE
Spike: Research Existing Aiops Features/ Offerings 

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#74]
In an effort to drive opensource AIOps for CI/CD, we want to ensure that we have a complete and up to date understanding of what features are available, being developed, and considered state-of-the-art both in industry and in the opensource community. To start we will do a research spike, identifying the existing offerings by leading AIOps service providers.       

Acceptance Criteria:
 
- [ ] Open an issue outlining an opensource alternative to an offering provided for each leading AIOps service provider.

**Some existing providers** 

- [ ] [Logz.io](https://logz.io/) 
- [ ] [Sumologic](https://www.sumologic.com/)
- [ ] [Zebrium](https://www.zebrium.com/)
- [ ] [Dynatrace](https://www.dynatrace.com/)
- [ ] log portal

**Comment by oindrillac** [comment]
completed by https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/docs/aiml-cicd-market-research.md
