### ISSUE TITLE
Public KPI Dashboard (initial draft)

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#78]
**Is your feature request related to a problem? Please describe.**
A publicly available dashboard to display and share our CI metrics. 

**Describe the solution you'd like**

- [ ] A Superset dashboard running on the [MOC-ODH operate first instance](https://superset-opf-superset.apps.cnv.massopen.cloud/). 
- [ ] Publicly available
- [ ] Monitoring in place to measure usage

**Comment by MichaelClifford** [comment]
@hemajv can we move this out of the backlog this sprint?

**Comment by oindrillac** [comment]
blocked by https://github.com/aicoe-aiops/ocp-ci-analysis/issues/344

**Comment by oindrillac** [comment]
We created a Public KPI Dashboard for various metrics on a [temporary DevConf cluster](https://superset.apps.devconfus2021.aws.operate-first.cloud/superset/dashboard/ocp-ci-kpi-dashboard/) and presented the dashboard at DevConf.US. 


https://user-images.githubusercontent.com/32435206/132698833-bb89c676-4d56-43b3-8f39-140997b1d8f1.mov


Once operate first zero/smaug is back up again, we will recreate our tables and the dashboards. Currently blocked on https://operatefirst.slack.com/archives/C01RT0NNCP7/p1631109919006400

**Comment by MichaelClifford** [comment]
Can you export the dashboard and save it to the repo so that 1) it does not need to be manually recreated 2) we can keep it tracked with git?

**Comment by oindrillac** [comment]
this dashboard was decommissioned before we could get to exporting it. But we should make sure to track all future dashboards in git.

**Comment by oindrillac** [comment]
completed by https://github.com/aicoe-aiops/ocp-ci-analysis/pull/400
