### ISSUE TITLE
Spike: Look into test grid data as potential issues classification problem.

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#8]
* [Testgrid](https://testgrid.k8s.io/redhat-openshift-okd-release-4.5-blocking#release-openshift-okd-installer-e2e-aws-4.5)

Given the image below, it appears that a human expert can determine the types of errors occurring based on the patterns present in the test grid. 

Is it possible for us to develop an automated method for doing the same? 

![image](https://user-images.githubusercontent.com/161888/89903201-a62b3800-dbe7-11ea-9b1c-2ec62fe8952f.png)

**Comment by SankBad** [comment]
Is it possible to get the data in the above format (grid-like) for this particular analysis?
Just for fun, I was trying to do so experiment on this data but the downloaded data is in a different format, (it's in the format as you have shown in your initial_EDA.ipynb)

**Comment by MichaelClifford** [comment]
@SankBad thanks for taking a look at this issue. :+1: 

Yes, it should be possible to get the data in the above grid format as a 2d array. But you are right the initial EDA does not have this data. 

Part of these issue should be getting access to this data and in the correct format for analysis.

**Comment by MichaelClifford** [comment]
This issue should fold in under #15
