### ISSUE TITLE
README to outline the `notebooks` dir structure

### ISSUE THREAD

**Issue by hemajv** [aicoe-aiops/ocp-ci-analysis#88]
**Is your feature request related to a problem? Please describe.**
Navigating through the `notebooks` directory is not as self-explanatory, as there are multiple folders in which different notebooks can be found. For example, `background` and `stage` folders.

It would be good to have a documentation that briefly describes these folders and the notebooks they consist of.

**Describe the solution you'd like**
A README within the `notebooks` directory outlining the directory structure. This will make it easier for others to understand and navigate through the repo.

**Comment by MichaelClifford** [comment]
@hemajv :+1:
