### ISSUE TITLE
Minor issues in the `failure_type_classifier` and `Sippy` notebooks

### ISSUE THREAD

**Issue by hemajv** [aicoe-aiops/ocp-ci-analysis#92]
**Describe the bug**
As a consumer of the `failure_type_classifier` and `Sippy` notebooks, I would like to read and run all the cells without any errors. Currently some of the relative links don't work possibly because of restructuring of the project.

**To Reproduce**
1. Go to [notebook](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/failure-type-classification/stage/failure_type_classifier.ipynb)
2. Run cell 4
**Expected behavior**
Change `..` to `../../..`

1. Go to [notebook 1](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/data-sources/Sippy/sippy_failure_correlation.ipynb) and [notebook 2](https://github.com/aicoe-aiops/ocp-ci-analysis/tree/master/notebooks/data-sources/Sippy/stage)
2. Run cell 2
**Expected behavior**
Point `../data/external/sippydata.json` to appropriate file (current file doesn't seem to exist in the repo)

**Acceptance Criteria**
- [x] Fix all relative links
- [x] Add missing data files

**Comment by hemajv** [comment]
@MichaelClifford in the [Sippy notebooks](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/data-sources/Sippy/sippy_failure_correlation.ipynb), there seems to be a missing data set: `/data/external/sippydata.json`, is this file located somewhere else in the repo?

**Comment by MichaelClifford** [comment]
@hemajv It looks like this dataset never got uploaded to the repo. I'll add a PR to include it
