### ISSUE TITLE
Pandas profiling package dependency

### ISSUE THREAD

**Issue by hemajv** [aicoe-aiops/ocp-ci-analysis#99]
**Describe the bug**

In the `sippy_EDA` notebook: https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/data-sources/Sippy/stage/sippy_EDA.ipynb
the `pandas_profiling` package is being used and when you install the package and run`profile.to_widgets()`, it throws this error:
```
TraitError: The 'value' trait of a HTML instance must be a unicode string, but a value of Numeric <class 'visions.types.type.VisionsBaseTypeMeta'> was specified.
```
Seems like this error is observed in `v2.10.0`: https://github.com/pandas-profiling/pandas-profiling/issues/668

**To Reproduce**
1. Go to [sippy_EDA notebook](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/data-sources/Sippy/stage/sippy_EDA.ipynb)
2. Run cells 1-11

**Expected behavior**
Pipfile and notebook should be updated to install the compatible version of the `pandas-profiling` package

**Comment by chauhankaranraj** [comment]
@hemajv Are you working on fixing this? If not, I'm happy to :smile:

**Comment by hemajv** [comment]
@chauhankaranraj sure go ahead! :smiley:
